import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Website",
  description: "Generated by Yasmine Hamaili",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        {/* Add Font Awesome Kit Script */}
        <script src="https://kit.fontawesome.com/b246a2cb9e.js" crossOrigin="anonymous" async></script>
        
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* IcoMoon Sprite */}
        <svg xmlns="http://www.w3.org/2000/svg" style={{ display: "none" }} aria-hidden="true">

          <symbol id="icon-myLogo" viewBox="0 0 32 32">
            <path d="M16 0C7.163 0 0 7.163 0 16c0 ..." />
          </symbol>
        </svg>
        {children}
        
      </body>
    </html>
  );
}
