import React from 'react'
import Image from 'next/image'
import style from './Footer.module.css'
const Footer = () => {
  return (
    <>
    <footer className={style.footer} id='footer'>
      <div className={style.logo}>
        <Image className={style.img} src='/images/myLogo.png' alt='logo' height={50} width={40}/>
        <h5 className={style.h5}>Generated by Yasmine Hamaili</h5>
      </div>
      <div className={style.contact}>
        <div className={style.phone}>
          <i className={`${style.icon} fa-solid fa-phone`}></i>
          <p className={style.text}>+123456789</p>
        </div>
        <div className={style.email}>
          <i className={`${style.icon} fa-solid fa-envelope`}></i>
          <p className={style.text}>email@gmail.com</p>
        </div>
      </div>
    </footer>
      
    </>
  )
}

export default Footer
